JCC = javac
JFLAGS = -g

default: cartas/carta.class cartas/Ramos.class cartas/Estudio.class cartas/Evento.class otros/mano.class otros/mazo.class otros/tablero.class juego.class

cartas/carta.class: cartas/carta.java
		$(JCC) $(JFLAGS) cartas/carta.java

cartas/Ramos.class: cartas/Ramos.java
		$(JCC) $(JFLAGS) cartas/Ramos.java

cartas/Estudio.class: cartas/Estudio.java
		$(JCC) $(JFLAGS) cartas/Estudio.java

cartas/Evento.class: cartas/Evento.java
		$(JCC) $(JFLAGS) cartas/Evento.java

otros/mano.class: otros/mano.java
		$(JCC) $(JFLAGS) otros/mano.java

otros/mazo.class: otros/mazo.java
		$(JCC) $(JFLAGS) otros/mazo.java
	
otros/tablero.class: otros/tablero.java
		$(JCC) $(JFLAGS) otros/tablero.java

juego.class: juego.java
		$(JCC) $(JFLAGS) juego.java

clean: 
		$(RM) cartas/*.class
		$(RM) otros/*.class
		$(RM) *.class